CREATE DATABASE SENAI_SPMEDGROUP_2TT_ALINE

USE SENAI_SPMEDGROUP_2TT_ALINE

--Criação de todas as tabelas de acordo com a situação problema (especialidades, médicos, administradores, pacientes, consultas, prontuários, clínicas)
CREATE TABLE ESPECIALIDADES(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (250) NOT NULL UNIQUE
);

CREATE TABLE MEDICOS(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (250) NOT NULL 
	,CRM CHAR (5) NOT NULL UNIQUE
	,ID_ESPECIALIDADE INT FOREIGN KEY REFERENCES ESPECIALIDADES(ID) NOT NULL
	,ID_CLINICA INT FOREIGN KEY REFERENCES CLINICA(ID) NOT NULL
	,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIO(ID) NOT NULL
);

CREATE TABLE CLINICA(
	ID INT IDENTITY PRIMARY KEY
	,NOME_FANTASIA VARCHAR(250) NOT NULL
	,CNPJ CHAR (14) NOT NULL UNIQUE
	,RAZAO_SOCIAL VARCHAR (250) NOT NULL
	,ENDERECO VARCHAR (250) NOT NULL UNIQUE
);
	
ALTER TABLE CLINICA ADD HORARIO_FUNCIONAMENTO VARCHAR (250); 

CREATE TABLE PRONTUARIO(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (250) NOT NULL
	,DATA_DE_NASCIMENTO DATETIME NOT NULL
	,TELEFONE VARCHAR(250) NOT NULL 
	,RG VARCHAR(20) NOT NULL UNIQUE
	,CPF VARCHAR(20) NOT NULL UNIQUE
	,ENDERECO VARCHAR (250) NOT NULL
	,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIO(ID) NOT NULL
);

CREATE TABLE CONSULTA(
	ID INT IDENTITY PRIMARY KEY
	,ID_PRONTUARIO INT FOREIGN KEY REFERENCES PRONTUARIO(ID) NOT NULL
	,ID_MEDICO INT FOREIGN KEY REFERENCES MEDICOS(ID) NOT NULL
	,DATA_CONSULTA DATETIME NOT NULL
	,ID_SITUACAO INT FOREIGN KEY REFERENCES SITUACAO(ID) NOT NULL
	,DESCRICAO TEXT 
);


CREATE TABLE SITUACAO(
	ID INT IDENTITY PRIMARY KEY
	,SITUACAO VARCHAR(250) NOT NULL UNIQUE
);


CREATE TABLE TIPO_DE_USUARIO(
	ID INT IDENTITY PRIMARY KEY
	,TIPO_DE_USUARIO VARCHAR(250) NOT NULL UNIQUE
);


CREATE TABLE USUARIO(
	ID INT IDENTITY PRIMARY KEY
	,EMAIL VARCHAR(250) NOT NULL UNIQUE
	,SENHA VARCHAR(250) NOT NULL
	,ID_TIPO_DE_USUARIO INT FOREIGN KEY REFERENCES TIPO_DE_USUARIO(ID) NOT NULL
);
